# Generated by Django 5.0.2 on 2025-03-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('page_number', models.IntegerField()),
                ('book_title', models.CharField(max_length=200)),
                ('purchase_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
