# Generated by Django 5.0.2 on 2025-03-14 14:53

from django.db import migrations

def populate_demo_books(apps, schema_editor):
    BookPage = apps.get_model('first_pages', 'BookPage')
    
    # Book 1: Mystery
    BookPage.objects.create(
        book_title="The Midnight Detective",
        title="Chapter 1: The Mysterious Letter",
        content="""The rain fell in sheets as Detective Sarah Mitchell stood at the entrance of the old Victorian mansion. The letter in her hand was barely legible, the ink smudged by the downpour. 'Meet me at midnight,' it read, 'if you want to know the truth about the missing paintings.' She checked her watch - 11:45 PM. Fifteen minutes to decide if this was a trap or her big break.""",
        page_number=1,
        purchase_link="https://example.com/midnight-detective"
    )
    
    # Book 2: Fantasy
    BookPage.objects.create(
        book_title="The Dragon's Legacy",
        title="Prologue: The Last Dragon",
        content="""In a world where dragons were thought to be extinct, young Elara discovered an egg in the depths of the Crystal Caves. The egg pulsed with an otherworldly light, and as she reached out to touch it, she felt a connection unlike anything she had ever known. This was no ordinary egg - this was the last dragon egg in existence.""",
        page_number=1,
        purchase_link="https://example.com/dragon-legacy"
    )
    
    # Book 3: Science Fiction
    BookPage.objects.create(
        book_title="Beyond the Stars",
        title="Chapter 1: The Launch",
        content="""Commander James Chen stared at the countdown display: 10... 9... 8... The experimental quantum drive hummed beneath his feet. This wasn't just another mission - this was humanity's first attempt at faster-than-light travel. As the numbers continued to count down, he thought about his family back on Earth and wondered if he'd ever see them again.""",
        page_number=1,
        purchase_link="https://example.com/beyond-stars"
    )
    
    # Book 4: Romance
    BookPage.objects.create(
        book_title="Love in Paris",
        title="Chapter 1: The Café",
        content="""The aroma of freshly baked croissants filled the air as Marie sat at her usual table in Café de la Paix. The morning sun cast golden light through the windows, illuminating the dust motes dancing in the air. She was about to take her first sip of coffee when she noticed him - the handsome stranger who had just walked in, carrying a sketchbook and wearing a paint-splattered beret.""",
        page_number=1,
        purchase_link="https://example.com/love-paris"
    )
    
    # Book 5: Historical Fiction
    BookPage.objects.create(
        book_title="The Queen's Secret",
        title="Chapter 1: The Royal Court",
        content="""The year was 1558, and the court of Queen Elizabeth I buzzed with whispers of conspiracy. Lady Catherine Howard, newly appointed lady-in-waiting, stood in the shadows of the great hall, watching as the queen held court. She had been chosen for this position for one reason: to uncover the truth behind the mysterious death of the previous lady-in-waiting.""",
        page_number=1,
        purchase_link="https://example.com/queen-secret"
    )

def reverse_populate_demo_books(apps, schema_editor):
    BookPage = apps.get_model('first_pages', 'BookPage')
    BookPage.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('first_pages', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_demo_books, reverse_populate_demo_books),
    ]
